<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_score</name>
   <tag></tag>
   <elementGuidId>375cf578-1353-4956-93f2-305e24ad2c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#score</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='score']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>776272c1-3251-416d-8218-f8b8dfce0a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2a688fc3-273d-43df-8ac2-30d4d008bdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>score</value>
      <webElementGuid>be84e09c-6d8d-457e-a7f9-2866f4550dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>score</value>
      <webElementGuid>7dcb1968-9d46-472c-b6e7-c4e7308f2ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Score...</value>
      <webElementGuid>31784c2d-1ab1-4367-b86a-a9b4ee28adf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a248b869-c9db-4681-a1eb-a56005c13f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score&quot;)</value>
      <webElementGuid>eeaaf641-4b92-4722-95e2-a5ada7d33def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='score']</value>
      <webElementGuid>b62ac2e5-90be-4fd1-943a-01ccf5b70eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e223fc67-52ab-4728-9435-ce1af33d3d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'score' and @name = 'score' and @placeholder = 'Score...' and @type = 'text']</value>
      <webElementGuid>c8e9e5fe-8ac4-4a2d-a7ce-fb29ef81f540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
