<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Try to add you score_staticEmail2</name>
   <tag></tag>
   <elementGuidId>23cb9bc3-435f-409d-a5b5-d32e1eaeb973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#staticEmail2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='staticEmail2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5d9bb47-bda4-452c-b8b5-b6b37ce697b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-plaintext</value>
      <webElementGuid>26194299-966e-4081-a1d9-4fc87ac88560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>staticEmail2</value>
      <webElementGuid>f58b4a58-73f4-4f95-87b1-86d3bf14e83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9445b59-186e-41b6-ac46-b8cb6598c2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enter your score</value>
      <webElementGuid>c9bf79b3-eb15-455e-8645-cd642f63e95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;staticEmail2&quot;)</value>
      <webElementGuid>edf36bc4-c7ae-4883-b89a-0b7d5d604d75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='staticEmail2']</value>
      <webElementGuid>594b78e2-57b9-4de6-9192-696409bfe0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4373080-fcf5-4825-ae2c-7be853c6dde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'staticEmail2' and @type = 'text']</value>
      <webElementGuid>d1e7fefc-8386-4e6b-9be1-6167c4a693ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
